# Generated by Django 3.0.6 on 2020-06-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'managed': False, 'verbose_name_plural': 'Tiendas'},
        ),
    ]
