# Generated by Django 3.0.6 on 2020-06-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.URLField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('slug', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('cover_photo', models.TextField(blank=True, null=True)),
                ('web_site', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
    ]
