# Generated by Django 3.0.6 on 2020-06-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('shareable', models.BooleanField(blank=True, null=True)),
                ('validity', models.BooleanField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('owner', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('owner', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'file_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileValidity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('validity_start_date', models.DateTimeField(blank=True, null=True)),
                ('validity_end_date', models.DateTimeField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'file_validity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uri', models.URLField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'multimedia',
                'managed': False,
            },
        ),
    ]
