# Generated by Django 3.0.6 on 2020-06-01 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSharingHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('all_role', models.BooleanField(blank=True, null=True)),
                ('all_division', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin_sharing_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('session_limit', models.IntegerField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'application',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationAccess',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'application_access',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('os', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('supported', models.BooleanField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'app_version',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColorStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'color_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('user_facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('user_instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_disabled', models.BooleanField()),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('address_add_on', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'contact_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'division',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DivisionType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('plural_name', models.CharField(blank=True, max_length=255, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'division',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('shareable', models.BooleanField(blank=True, null=True)),
                ('validity', models.BooleanField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('owner', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('owner', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'file_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileValidity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('validity_start_date', models.DateTimeField(blank=True, null=True)),
                ('validity_end_date', models.DateTimeField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'file_validity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuardianTokens',
            fields=[
                ('jti', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('aud', models.CharField(max_length=255)),
                ('typ', models.CharField(blank=True, max_length=255, null=True)),
                ('iss', models.CharField(blank=True, max_length=255, null=True)),
                ('sub', models.CharField(blank=True, max_length=255, null=True)),
                ('exp', models.BigIntegerField(blank=True, null=True)),
                ('jwt', models.TextField(blank=True, null=True)),
                ('claims', models.TextField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'guardian_tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'indicator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndicatorSharingHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'indicator_sharing_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('owner', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MessageCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('owner', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'message_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uri', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'multimedia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationOpting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'notification_opting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pqr',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'pqr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_code', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('owner', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('owner', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('validity', models.BooleanField(blank=True, null=True)),
                ('visibility', models.BooleanField(blank=True, null=True)),
                ('link_visibility', models.BooleanField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('reference_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'product_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductValidity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('validity_start_date', models.DateTimeField(blank=True, null=True)),
                ('validity_end_date', models.DateTimeField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'product_validity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'roles_permisions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchemaMigrations',
            fields=[
                ('version', models.BigIntegerField(primary_key=True, serialize=False)),
                ('inserted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'schema_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('os', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('firebase_token', models.TextField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('device_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('device_model', models.CharField(blank=True, max_length=255, null=True)),
                ('device_version', models.CharField(blank=True, max_length=255, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SharingInfoContact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=360, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('so', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sharing_info_contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('type_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'shortcut',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShortcutApp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('android_url', models.CharField(blank=True, max_length=255, null=True)),
                ('ios_url', models.CharField(blank=True, max_length=255, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'shortcut_app',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShortcutMail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('destinatary', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shortcut_mail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShortcutWeb',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'shortcut_web',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('link_facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('link_youtube', models.CharField(blank=True, max_length=255, null=True)),
                ('link_pinterest', models.CharField(blank=True, max_length=255, null=True)),
                ('link_instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('web_site', models.CharField(blank=True, max_length=255, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'store',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TempMultimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.TextField(blank=True, null=True)),
                ('type', models.FloatField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('entity_type', models.TextField(blank=True, null=True)),
                ('sku', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temp_multimedia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TemporalProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('sku', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temporal_product_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TempProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_code', models.TextField(blank=True, null=True)),
                ('categoria3', models.TextField(blank=True, null=True)),
                ('idzona', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temp_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('picture', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('in_division_status', models.BooleanField(blank=True, null=True)),
                ('os', models.CharField(blank=True, max_length=255, null=True)),
                ('validation_code', models.TextField(blank=True, null=True)),
                ('code_validated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_keyboard', models.BooleanField(blank=True, null=True)),
                ('first_use', models.BooleanField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserStore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_store',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('critical_version', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=255, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('minimal_version', models.CharField(blank=True, max_length=255, null=True)),
                ('os', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'version',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.User')),
                ('division_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_disabled', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_company',
                'managed': False,
            },
        ),
    ]
