# Generated by Django 3.0.6 on 2020-06-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200608_2055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
        migrations.DeleteModel(
            name='ProductValidity',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': False, 'verbose_name_plural': 'Contacto'},
        ),
        migrations.AlterModelOptions(
            name='contactstatus',
            options={'managed': False, 'verbose_name_plural': 'Estado del contacto'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'managed': False, 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='messagecategory',
            options={'managed': False, 'verbose_name_plural': 'Categoria del mensaje'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'managed': False, 'verbose_name_plural': 'Sesiones'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='usercompany',
            options={'managed': False, 'verbose_name_plural': 'Usuario en compañia'},
        ),
        migrations.AlterModelOptions(
            name='userstore',
            options={'managed': False, 'verbose_name_plural': 'Usuario en tienda'},
        ),
    ]
