# Generated by Django 3.0.6 on 2020-06-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('reference_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Codigo de referencia')),
                ('alias', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alias')),
                ('inserted_at', models.DateTimeField(verbose_name='Ingresado en')),
                ('updated_at', models.DateTimeField(verbose_name='Actualizado en')),
                ('owner', models.CharField(max_length=255, verbose_name='Propietario')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='Nivel')),
                ('inserted_at', models.DateTimeField(verbose_name='Ingresado en')),
                ('updated_at', models.DateTimeField(verbose_name='Actualizado en')),
                ('owner', models.CharField(max_length=255, verbose_name='Propietario')),
            ],
            options={
                'verbose_name_plural': 'Categoria de producto',
                'db_table': 'product_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('validity', models.BooleanField(blank=True, null=True, verbose_name='Validez')),
                ('visibility', models.BooleanField(blank=True, null=True, verbose_name='Visibilidad')),
                ('link_visibility', models.BooleanField(blank=True, null=True, verbose_name='Visibilidad de link')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Precio')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Moneda')),
                ('inserted_at', models.DateTimeField(verbose_name='Ingresado en')),
                ('updated_at', models.DateTimeField(verbose_name='Actualizado en')),
                ('reference_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Codigo de referencia')),
            ],
            options={
                'verbose_name_plural': 'Detalles de producto',
                'db_table': 'product_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductValidity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Precio')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Moneda')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('validity_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha inicial de validez')),
                ('validity_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha final de validez')),
                ('inserted_at', models.DateTimeField(verbose_name='Ingresado en')),
                ('updated_at', models.DateTimeField(verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name_plural': 'Validez de producto',
                'db_table': 'product_validity',
                'managed': False,
            },
        ),
    ]
